### ISSUE TITLE
Publish on open-vsx

### ISSUE THREAD

**Issue by sonnyp** [ctlajoie/vscode-modelines#18]
Hello,

Thank you for this extension. Could you publish it on https://open-vsx.org/ so that users of [VSCodium](https://vscodium.com/) can install it easily?

https://open-vsx.org/

**Comment by martin-braun** [comment]
@ctlajoie This is pretty important for me as well. Could you please consider to publish your great extension over there? We don't like telemetry by M$. :)

**Comment by ctlajoie** [comment]
@martin-braun I am working on getting it published on open-vsx.org. Currently waiting for them to approve ownership of the chrislajoie namespace. 

https://github.com/EclipseFdn/open-vsx.org/issues/1987

**Comment by ctlajoie** [comment]
The extension has been published on open-vsx.org

https://open-vsx.org/extension/chrislajoie/vscode-modelines

**Comment by martin-braun** [comment]
@ctlajoie Thank you for your service, it works like charm. :)
