### ISSUE TITLE
Set language with modeline

### ISSUE THREAD

**Issue by ffes** [ctlajoie/vscode-modelines#2]
In the readme is a section Limitations. I understand that at the moment of writing it was not possible to change the language used for syntax highlighting.

I found the open issue with your feature request to the vscode team. Could you add a link to https://github.com/Microsoft/vscode/issues/1800 in the readme? Maybe more modeline users can upvote the issue a bit ;-)

**Comment by ctlajoie** [comment]
Agreed. Thanks for taking the time to point that out.

**Comment by jakubzitny** [comment]
Any update on this @ctlajoie, please?

**Comment by ffes** [comment]
Did you see @mechatroner opened the PR https://github.com/Microsoft/vscode/pull/55107 to fix the issue in vscode?

**Comment by ffes** [comment]
I'm sure you noticed that Microsoft/vscode#1800 has been fixed a couple of days ago.

So the original feature request should be implementable now \o/

**Comment by ffes** [comment]
VS Code v1.28 is released and should contain the API needed for this feature:
https://code.visualstudio.com/updates/v1_28#_change-the-language-of-a-text-document

**Comment by ctlajoie** [comment]
@ffes thanks for the heads up. I'll see if I can get it implemented now. PRs also welcome.

**Comment by ctlajoie** [comment]
@ffes Finally, this has been implemented. ebb518d998f0b3ec5dd27bc6d99d4ed08231cc07
