### ISSUE TITLE
support vi `syntax` as another synonym for `language`

### ISSUE THREAD

**Issue by mcandre** [ctlajoie/vscode-modelines#20]
The variable `syntax` is said to be backwards compatible with vi, and therefore preferred over `filetype` / `ft`.

GitHub Linguist supports `syntax` as well.

https://chrisarcand.com/manually-setting-languages-on-github-with-linguists-improved-vim-modeline-detection/

**Comment by mcandre** [comment]
Uploaded pull request for this.

https://github.com/ctlajoie/vscode-modelines/pull/21

**Comment by ctlajoie** [comment]
I have merged #21
