### ISSUE TITLE
How do I set shell script as a language?

### ISSUE THREAD

**Issue by agross** [ctlajoie/vscode-modelines#3]
Hi,

I'm looking forward to using modelines in my shell scripts. Unfortunately Code only supports `shellscript` while there are at least three different kinds of shell scripts:

* sh
* zsh
* bash
* fish, ksh, etc.

I'm specifically interested in zsh since this is my main shell. There are also some bash scripts in my dotfiles without extensions.

I tried setting `# vim: set ft=zsh ts=2 sw=2 et:` as the first line of a file to see if I get syntax highlighting. vim detects the language accordingly and highlights the syntax. Code (with your extension) doesn't detect the file as shell (`sh`), even after I `Apply modelines`. `ft=sh` also does not seem to work in all cases.

Here's an example: https://github.com/agross/dotfiles/blob/master/zsh/zshrc

Do you have any suggestions why that might be the case?

**Comment by agross** [comment]
Interesting, after looking at the source code of your extension I see that lines like these are being logged:

```
[modelines] setting editor options: {"language":"zsh"}
```

VS Code remains in "Plain text" mode, though.

**Comment by agross** [comment]
Alright, `# vim:set filetype=shellscript:` works, but that is not supported by vim. Could you please map `sh` and `zsh` to `shellscript`?

**Comment by agross** [comment]
It looks like the builtin shell script language already has that mapping as an alias, perhaps you could use that: https://github.com/Microsoft/vscode/blob/master/extensions/shellscript/package.json#L14

**Comment by cciotti** [comment]
It only seems to work with `# vim:set filetype=shellscript:` I've tried using `# vim:set filetype=sh:` and when I reopen the file, it's ignored (same for the others). I'm using VS Code Version 1.28.2 (1.28.2) and Modelines 2.0.1

**Comment by ctlajoie** [comment]
I can add more aliases for those shell types you listed.

**Comment by ctlajoie** [comment]
Done in 3e91a390d1eed7e7062f8d4ec7454b6d41db7ef7. Thanks for reporting.

**Comment by agross** [comment]
Thanks!
